######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 9 11:15:16 2011
######################################################################

TEMPLATE = app
TARGET = ssh-askpass
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += ..
INCLUDEPATH += ../gui

# Input
HEADERS += \
    ../gui/PasswordDialog.hpp

FORMS += \
    ../gui/PasswordDialog.ui

SOURCES += \
    ../gui/PasswordDialog.cpp \
    GnosticSshAskpass.cpp

